# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
plazos <- function(monto, tasa, pago) {
    .Call('_ValidacionCredito_plazos', PACKAGE = 'ValidacionCredito', monto, tasa, pago)
}

#' @title
#' Cuota de pago mensual
#'
#' @description
#' Calcula la cuota de pago mensual siguiendo la fórmula:
#'
#' \deqn{A = P (\frac{i (1 + i)^{n}}{(1 + i)^{n} - 1}))}
#'
#' para i > 0. Si i = 0, entonces simplemente:
#'
#' \deqn{A = P/n}
#'
#' @param monto  [double(1)]\cr Monto del prestamo
#' @param tasa   [double(1)]\cr Tasa de interés del préstamo
#' @param plazos [int(1)]\cr Plazo del crédito
#'
#' @export
cuota <- function(monto, tasa, plazos) {
    .Call('_ValidacionCredito_cuota', PACKAGE = 'ValidacionCredito', monto, tasa, plazos)
}

#' @title
#' Ceiling quincenal
#'
#' @description
#' Devuelve la fecha de corte
#'
#' @param fecha  [Date(1): required]\cr Fecha de la cual calcular la quincena
#'
#' @return
#' [Date(1)] Próxima quincena
#'
#' @export
ceiling_fecha <- function(fechas, pagos_mensuales) {
    .Call('_ValidacionCredito_ceiling_fecha', PACKAGE = 'ValidacionCredito', fechas, pagos_mensuales)
}

#' @title
#' Tabla de amortización
#'
#' @description
#' Calcula la tabla de amortización lo más cercano posible a como lo hacen
#' algunas instituciones de crédito. Este método es un método iterativo que ocupa varios
#' redondeos en múltiples fases del proceso. Para entender exactamente en que
#' momentos y en que valores se hacen los redondeos, se recomienda leer el
#' código fuente.
#'
#' @inheritParams         cuota
#' @param fecha_inicial   [Date(1)]\cr Fecha de vencimiento de la primera cuota
#' @param pagos_mensuales [int(1)]\cr Número de cuotas mensuales
#'
#' @export
amortizacion <- function(monto, tasa, plazos, fecha_inicial, pagos_mensuales) {
    .Call('_ValidacionCredito_amortizacion', PACKAGE = 'ValidacionCredito', monto, tasa, plazos, fecha_inicial, pagos_mensuales)
}

#' @export
round_away_ <- function(x, n = 0L) {
    .Call('_ValidacionCredito_round_away_', PACKAGE = 'ValidacionCredito', x, n)
}

#' @title
#' Redondear hacia afuera con un algoritmo en específico usado por algunas instituciones de crédito.
#'
#' @param x  [double(1)]\cr Number to round.
#' @param n  [int(1)]\cr Number of decimal places to round to.
#'
#' @export
round_away <- function(x, n = 0L) {
    .Call('_ValidacionCredito_round_away', PACKAGE = 'ValidacionCredito', x, n)
}

#' @export
fechas_de_pago <- function(fecha_inicial, plazos, pagos_mensuales) {
    .Call('_ValidacionCredito_fechas_de_pago', PACKAGE = 'ValidacionCredito', fecha_inicial, plazos, pagos_mensuales)
}

#' @export
sequence_fechas <- function(fecha_inicial, fecha_final, pagos_mensuales) {
    .Call('_ValidacionCredito_sequence_fechas', PACKAGE = 'ValidacionCredito', fecha_inicial, fecha_final, pagos_mensuales)
}

#' @title
#' Saldos Reales
#'
#' @description
#' Calcula el saldo real en todos los periodos por medio de la aplicación de
#' pagos registrados.
#'
#' @param DT Data.table que contiene el desglose de los saldos teóricos y
#' las aplpicaciónes de pagos.
#'
#' @export
saldo_en_t <- function(DT) {
    .Call('_ValidacionCredito_saldo_en_t', PACKAGE = 'ValidacionCredito', DT)
}

